
mission:
  arm_required : False
  nav_required : False

yolo:
  weights_path: '/home/andrii/Gus2/networks/yolo_asparagus/model.engine'
  iou_threshold: 0.8
  class_threshold: 0.85
  num_masks: 32
  input_height: 480
  input_width: 640
  img_height: 480
  img_width: 640

working_area:
  ignore_distance: 1000
  min_distance_w_no_angle_correction: 400
  max_reachable_distance: 700

asparagus:
  topk: 0.05
  botk: 0.05
  n_skeletons: 20
  min_lenht: 150


streamer:
  ip: 192.168.1.232
  port: 5000


end_effector:
  x_start: -30
  y_start: -30
  z_start: 1

  x_dim: 15
  y_dim: 15
  z_dim: 15

  blade_x_off: 7.5
  blade_y_off: 3
  blade_z_off: 1

  danger_zone_x: 3
  danger_zone_y: 3
  danger_zone_z: 0

  approach_distance: 20

brute_planner:
  min_angle : -45
  max_angle : 45
  resolution : 5




