# Example YAML Configuration File for a Web Server

# Server Configuration
yolo:
  weights_path: '/home/andrii/Gus2/networks/yolo_asparagus/model.engine'
  iou_threshold: 0.8
  class_threshold: 0.85
  num_masks: 32
  input_height: 480
  input_width: 640
  img_height: 480
  img_width: 640

working_area:
  ignore_distance: 1000
  min_distance_w_no_angle_correction: 400
  max_reachable_distance: 550

asparagus:
  topk: 0.05
  botk: 0.05
  n_skeletons: 15
  min_lenht: 150


streamer:
  ip: 192.168.1.108
  port: 5000


