
mission:
  arm_required : True
  nav_required : False

yolo:
  weights_path: '/home/andrii/Gus2/networks/yolo_asparagus/model.engine'
  iou_threshold: 0.8
  class_threshold: 0.85
  num_masks: 32
  input_height: 480
  input_width: 640
  img_height: 480
  img_width: 640

working_area:
  ignore_distance: 1000
  min_distance_w_no_angle_correction: 400
  max_reachable_distance: 700

asparagus:
  topk: 0.05
  botk: 0.05
  n_skeletons: 20
  min_lenht: 10


streamer:
  ip: 192.168.1.108
  port: 5000


end_effector:
  x_start: 0
  y_start: 0
  z_start: 0

  x_dim: 100
  y_dim: 150
  z_dim: 150

  blade_x_off: 50
  blade_y_off: 10
  blade_z_off: 10

  danger_zone_x: 30
  danger_zone_y: 30
  danger_zone_z: 0

  approach_distance: 100



brute_planner:
  min_angle : -90
  max_angle : 90
  resolution : 5




